# Use this notbook for your 3 choices of APIs

In [127]:
# Import requests library
import requests
import pandas as pd

dog = requests.get("https://dogapi.dog/api-docs/v2/swagger.json")
print(dog.status_code)

200

In [128]:
import json
dog = dog.json()

In [129]:
from pandas import json_normalize
dataX = requests.get('https://dogapi.dog/api-docs/v2/swagger.json').json()
dataX2 = json_normalize(dataX)
dataX2.shape
dataX2

,openapi,servers,info.title,info.version,info.description,info.termsOfService,info.contact.email,info.license.name,info.license.url,paths./breeds.get.summary,...,paths./groups.get.responses.200.content.application/json.examples.example.value.links.last,paths./groups/{id}.get.summary,paths./groups/{id}.get.tags,paths./groups/{id}.get.parameters,paths./groups/{id}.get.responses.200.description,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.id,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.type,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.name,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.relationships.breeds.data,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.links.self
0,3.0.1,[{'url': 'https://dogapi.dog/api/v2'}],API V2,1.0.0,The Dog API provides a wealth of information o...,https://dogapi.dog/terms,dev@dogapi.dog,MIT,https://github.com/kinduff/dogapi.dog/blob/mas...,list breeds,...,https://dogapi.dog/api/v2/groups?page[number]=2,get group,[Groups],"[{'name': 'id', 'in': 'path', 'required': True...",successful,02124eb6-1baa-410c-90ea-6b8629fb0837,group,Foundation Stock Service,[{'id': 'b0b6810c-fb88-4987-ad0a-ae0440b04634'...,https://dogapi.dog/api/v2/groups/02124eb6-1baa...

In [79]:
dataX2.columns

Index(['openapi', 'servers', 'info.title', 'info.version', 'info.description',
       'info.termsOfService', 'info.contact.email', 'info.license.name',
       'info.license.url', 'paths./breeds.get.summary',
       'paths./breeds.get.tags', 'paths./breeds.get.responses.200.description',
       'paths./breeds.get.responses.200.content.application/json.examples.example.value.data',
       'paths./breeds.get.responses.200.content.application/json.examples.example.value.links.self',
       'paths./breeds.get.responses.200.content.application/json.examples.example.value.links.current',
       'paths./breeds.get.responses.200.content.application/json.examples.example.value.links.next',
       'paths./breeds.get.responses.200.content.application/json.examples.example.value.links.last',
       'paths./breeds/{id}.get.summary', 'paths./breeds/{id}.get.tags',
       'paths./breeds/{id}.get.parameters',
       'paths./breeds/{id}.get.responses.200.description',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.id',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.type',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.name',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.min_life',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.max_life',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.description',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.hypoallergenic',
       'paths./breeds/{id}.get.responses.200.content.application/json.examples.example.value.links.self',
       'paths./facts.get.summary', 'paths./facts.get.tags',
       'paths./facts.get.parameters',
       'paths./facts.get.responses.200.description',
       'paths./facts.get.responses.200.content.application/json.examples.example.value.data',
       'paths./groups.get.summary', 'paths./groups.get.tags',
       'paths./groups.get.responses.200.description',
       'paths./groups.get.responses.200.content.application/json.examples.example.value.data',
       'paths./groups.get.responses.200.content.application/json.examples.example.value.links.self',
       'paths./groups.get.responses.200.content.application/json.examples.example.value.links.current',
       'paths./groups.get.responses.200.content.application/json.examples.example.value.links.next',
       'paths./groups.get.responses.200.content.application/json.examples.example.value.links.last',
       'paths./groups/{id}.get.summary', 'paths./groups/{id}.get.tags',
       'paths./groups/{id}.get.parameters',
       'paths./groups/{id}.get.responses.200.description',
       'paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.id',
       'paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.type',
       'paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.name',
       'paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.relationships.breeds.data',
       'paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.links.self'],
      dtype='object')

In [137]:
dataX2[['info.description']]

                                    info.description
0  The Dog API provides a wealth of information o...

# Fruityvice: Data about all kinds of fruit

In [99]:
r = requests.get("https://fruityvice.com/api/fruit/all").json()

In [109]:
data = pd.DataFrame(r)
data.head()

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."

In [106]:
data['nutritions'][0]

{'carbohydrates': 11.4,
 'protein': 0.3,
 'fat': 0.4,
 'calories': 52,
 'sugar': 10.3}

In [108]:
flattened_data = json_normalize(r)
flattened_data.head(5)

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.3,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.5,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.0,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.0,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.3,0.40,40,4.50

# Animal Crossing: New Horizons
### API for critters, fossils, art, music, furniture and villagers

In [110]:
r = requests.get("https://acnhapi.com/v1a/fish").json()

In [115]:
data = pd.DataFrame(r)
acdata = json_normalize(r)
acdata

,id,file-name,shadow,price,price-cj,catch-phrase,museum-phrase,image_uri,icon_uri,name.name-USen,...,availability.month-southern,availability.time,availability.isAllDay,availability.isAllYear,availability.location,availability.rarity,availability.month-array-northern,availability.month-array-southern,availability.time-array,alt-catch-phrase
0,1,bitterling,Smallest (1),900,1350,"I caught a bitterling! It's mad at me, but onl...",Bitterlings hide their eggs inside large bival...,https://acnhapi.com/v1/images/fish/1,https://acnhapi.com/v1/icons/fish/1,bitterling,...,5-9,,True,False,River,Common,"[11, 12, 1, 2, 3]","[5, 6, 7, 8, 9]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
1,2,pale_chub,Smallest (1),200,300,I caught a pale chub! That name seems a bit ju...,The pale chub is a river fish with simple back...,https://acnhapi.com/v1/images/fish/2,https://acnhapi.com/v1/icons/fish/2,pale chub,...,,9am - 4pm,False,True,River,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[9, 10, 11, 12, 13, 14, 15]",NaN
2,3,crucian_carp,Small (2),160,240,I caught a crucian carp! My skills are sharp!,I wonder... Do you know how to tell the differ...,https://acnhapi.com/v1/images/fish/3,https://acnhapi.com/v1/icons/fish/3,crucian carp,...,,,True,True,River,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
3,4,dace,Medium (3),240,360,I caught a dace! Hope I have some space!,Dace are shiny little fish that enjoy freshwat...,https://acnhapi.com/v1/images/fish/4,https://acnhapi.com/v1/icons/fish/4,dace,...,,4pm - 9am,False,True,River,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
4,5,carp,Medium (4),300,450,I caught a carp! If I catch another they can c...,"Oh, the carp... have you ever seen their teeth...",https://acnhapi.com/v1/images/fish/5,https://acnhapi.com/v1/icons/fish/5,carp,...,,,True,True,Pond,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
5,6,koi,Medium (4),4000,6000,I caught a koi! I don't know why it's so shy.....,Koi are a variety of carp bred for their color...,https://acnhapi.com/v1/images/fish/6,https://acnhapi.com/v1/icons/fish/6,koi,...,,4pm - 9am,False,True,Pond,Uncommon,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
6,7,goldfish,Smallest (1),1300,1950,I caught a goldfish! It's worth its weight in ...,Goldfish are so cute and delicate... but do yo...,https://acnhapi.com/v1/images/fish/7,https://acnhapi.com/v1/icons/fish/7,goldfish,...,,,True,True,Pond,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
7,8,pop-eyed_goldfish,Smallest (1),1300,1950,I got a pop-eyed goldfish! It looks so...surpr...,"Pop-eyed goldfish have, as the name suggests, ...",https://acnhapi.com/v1/images/fish/8,https://acnhapi.com/v1/icons/fish/8,pop-eyed goldfish,...,,9am - 4pm,False,True,Pond,Common,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[9, 10, 11, 12, 13, 14, 15]",NaN
8,9,ranchu_goldfish,Small (2),4500,6750,I caught a ranchu goldfish! But I prefer balsa...,The ranchu goldfish is a charming relative of ...,https://acnhapi.com/v1/images/fish/9,https://acnhapi.com/v1/icons/fish/9,ranchu goldfish,...,,9am - 4pm,False,True,Pond,Uncommon,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[9, 10, 11, 12, 13, 14, 15]",NaN
9,10,killifish,Smallest (1),300,450,I caught a killifish! The streams are safe again.,"Ah, the magnificent killifish! Did you know th...",https://acnhapi.com/v1/images/fish/10,https://acnhapi.com/v1/icons/fish/10,killifish,...,10-2,,True,False,Pond,Common,"[4, 5, 6, 7, 8]","[10, 11, 12, 1, 2]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
10,11,crawfish,Small (2),200,300,I caught a crawfish! Or else it's a lobster an...,Ohoo! So you have found a crawfish. Neither cr...,https://acnhapi.com/v1/images/fish/11,https://acnhapi.com/v1/icons/fish/11,crawfish,...,10-3,,True,False,Pond,Common,"[4, 5, 6, 7, 8, 9]","[10, 11, 12, 1, 2, 3]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
11,12,soft-shelled_turtle,Medium (4),3750,5625,I caught a soft-shelled turtle! I can really s...,These relatives of common turtles will not let...,https://acnhapi.com/v1/images/fish/12,https://acnhapi.com/v1/icons/fish/12,soft-shelled turtle,...,2-3,4pm - 9am,False,False,River,Uncommon,"[8, 9]","[2, 3]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",[I caught a soft-shelled turtle! I should take...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,mahi-mahi,Large (5),6000,9000,I caught a mahi-mahi! It's all mahine-mahine.,The mahi-mahi is an ocean fish known for its w...,https://acnhapi.com/v1/images/fish/69,https://acnhapi.com/v1/icons/fish/69,mahi-mahi,...,11-4,,True,False,Pier,Rare,"[5, 6, 7, 8, 9, 10]","[11, 12, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
69,70,ocean_sunfish,Largest with fin (6),4000,6000,I caught an ocean sunfish! Good thing I'm wear...,The ocean sunfish is a large relative of the b...,https://acnhapi.com/v1/images/fish/70,https://acnhapi.com/v1/icons/fish/70,ocean sunfish,...,1-3,4am - 9pm,False,False,Sea,Uncommon,"[7, 8, 9]","[1, 2, 3]","[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...",NaN
70,71,ray,Large (5),3000,4500,I caught a ray! A few more and I'll have a tan!,The ray is an unusually shaped fish with a fla...,https://acnhapi.com/v1/images/fish/71,https://acnhapi.com/v1/icons/fish/71,ray,...,2-5,4am - 9pm,False,False,Sea,Uncommon,"[8, 9, 10, 11]","[2, 3, 4, 5]","[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...",NaN
71,72,saw_shark,Largest with fin (6),12000,18000,I caught a saw shark! You could call it a sea ...,"As you might expect from the name, the saw sha...",https://acnhapi.com/v1/images/fish/72,https://acnhapi.com/v1/icons/fish/72,saw shark,...,12-3,4pm - 9am,False,False,Sea,Rare,"[6, 7, 8, 9]","[12, 1, 2, 3]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
72,73,hammerhead_shark,Largest with fin (6),8000,12000,I caught a hammerhead shark! I hit the nail on...,The hammerhead shark is known for its distinct...,https://acnhapi.com/v1/images/fish/73,https://acnhapi.com/v1/icons/fish/73,hammerhead shark,...,12-3,4pm - 9am,False,False,Sea,Uncommon,"[6, 7, 8, 9]","[12, 1, 2, 3]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
73,74,great_white_shark,Largest with fin (6),15000,22500,I caught a great white shark! Watch out for it...,Great white sharks are obviously known first a...,https://acnhapi.com/v1/images/fish/74,https://acnhapi.com/v1/icons/fish/74,great white shark,...,12-3,4pm - 9am,False,False,Sea,Rare,"[6, 7, 8, 9]","[12, 1, 2, 3]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
74,75,whale_shark,Largest with fin (6),13000,19500,Thar she blows! I caught a whale shark! I'm te...,The mighty whale shark is the largest species ...,https://acnhapi.com/v1/images/fish/75,https://acnhapi.com/v1/icons/fish/75,whale shark,...,12-3,,True,False,Sea,Rare,"[6, 7, 8, 9]","[12, 1, 2, 3]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
75,76,suckerfish,Medium with fin (4),1500,2250,I caught a suckerfish! I thought it was a shar...,The suckerfish is a curious fish that likes to...,https://acnhapi.com/v1/images/fish/76,https://acnhapi.com/v1/icons/fish/76,suckerfish,...,12-3,,True,False,Sea,Uncommon,"[6, 7, 8, 9]","[12, 1, 2, 3]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
76,77,football_fish,Medium (4),2500,3750,I caught a football fish! Some countries call ...,The football fish is a strange and grotesque d...,https://acnhapi.com/v1/images/fish/77,https://acnhapi.com/v1/icons/fish/77,football fish,...,5-9,4pm - 9am,False,False,Sea,Uncommon,"[11, 12, 1, 2, 3]","[5, 6, 7, 8, 9]","[16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4...",NaN
77,78,oarfish,Largest (6),9000,13500,I caught an oarfish! I hope I catch morefish!,"The oarfish is a long, eel-like fish that can ...",https://acnhapi.com/v1/images/fish/78,https://acnhapi.com/v1/icons/fish/78,oarfish,...,6-11,,True,False,Sea,Rare,"[12, 1, 2, 3, 4, 5]","[6, 7, 8, 9, 10, 11]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN
78,79,barreleye,Small (2),15000,22500,I caught a barreleye! Like eyeing fish in a ba...,The barreleye is a deep-sea fish with protuber...,https://acnhapi.com/v1/images/fish/79,https://acnhapi.com/v1/icons/fish/79,barreleye,...,,9pm - 4am,False,True,Sea,Ultra-rare,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[21, 22, 23, 0, 1, 2, 3]",NaN
79,80,coelacanth,Largest (6),15000,22500,Blast from the past! I caught a coelacanth! Th...,The coelacanth is a deep-sea fish that has bee...,https://acnhapi.com/v1/images/fish/80,https://acnhapi.com/v1/icons/fish/80,coelacanth,...,,,True,True,Sea (when raining or snowing),Ultra-rare,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",NaN

In [118]:
acdata['catch-phrase'][2]

'I caught a crucian carp! My skills are sharp!'

In [125]:
len(acdata)

80

In [122]:
import random

def random_catfact(acdata):
    print(data['catch-phrase'][random.randint(0, len(acdata)-1)])

In [124]:
random_catfact(acdata)

I caught a bitterling! It's mad at me, but only a little.

# germany

In [130]:
r = requests.get("https://slftool.github.io/data.json").json()

In [133]:
data = pd.DataFrame(r)
data.T

,stadt,land,fluss,name,beruf,tier,marke,pflanze
a,"[Aalen, Aachen, Amberg, Athen (Griechenland), ...","[Albanien, Armenien, Andorra, Algerien, Austra...","[Aller (Deutschland), Amazonas (Brasilien), Al...","[Alexander, Alexandra, Anette, Amanda, Anton]","[Atomphysiker, Anlagenbauer, Autor, Astronaut]","[Aul, Affe, Ara, Ameise, AmaisenbÃ¤r, Aal]","[Adidas, Abus, Alpina, Asics]","[Agave, Apfel, Avocado, Ananas, Ahorn, Alge]"
b,"[Bamberg, Bonn, BÃ¶blingen, Boston, Birmingham,...","[Belgien, Brasilien, Bolivien, Bermudas, Bahra...","[Bigge (Deutschland), Brahmaputra (u.a. Indien...","[Benjamin, Benny, Bernd, Barbara, Beate, Boris...","[Busfahrer, Beamter, Bundesminister, BÃ¤cker, B...","[BÃ¤r, Biene, Beluga, Biber, Bea, Bison, Blaume...","[Basil, Barbour, Bench, Billa Bong, Blomus, Bo...","[BÃ¤rlauch, Bartlilie, Begonie]"
c,"[Chemnitz (Deutschland), Cuxhaven (Deutschland...","[China, Costa Rica, Chile, Cookinseln]","[Chemnitz (Deutschland), Colorado (USA), Chare...","[Christian, Claus, Christoph, Conni, Clara]","[Chemiker, Chorleiter, Chauffeur, Chirurg]","[Chameleon, Chinchilla, Chiuahua, Clownfisch]","[C & A, Calvin Klein, Camper, Casio, CAT, Coac...","[Capuchina Kresse, Charlotte, Chilli, Christro..."
d,"[Dresden (Deutschland), Dortmund (Deutschland)...","[Deutschland, DÃ¤nemark, Dominikanische Republi...","[Donau (Europa), Don (Russland), Dnister (Ukra...","[Daniel, Dennis, Dora, Detlef]","[Doktor, DomtÃ¶r, Dachdecker, Designer, Drogist]","[Dachs, Diamanttaube, Dingo, Distelfink, Dorsc...","[Dakine, DeinDesign, Diesel, Dockers, Domo]","[Dattel, Diestel, Dahlie]"
e,"[Essen (Deutschland), Esslingen (Deutschland),...","[Estland, Ecuador, El Salvador, Eritrea]","[Ems (Deutschland), Emscher (Deutschland), Elb...","[Emma, Elara, Erika, Ella, Emil, Edgar]","[Elektriker, Estrichleger, Erzieher, Eisenbahner]","[Esel, Elephant, Emo, EichelhÃ¤her]","[Eastpak, Ecco, Edding, Einhell, Ergobag, Espr...","[Erbse, Eichel, Erdenuss, Erdbeere, Efeu]"
f,"[Frankfurt (Main/Oder) (Deutschland), FÃ¼rth (D...","[Finnland, Frankreich, Fidschi]","[Fulda (Deutschland), Fraser River (Kanada), F...","[Friderike, Frida, Florin, Fritz, Franz, Franz...","[Fliesenleger, Friseur, Falkner]","[Fischotter, Felsentaube, Frettchen]","[Fendi, Faber Castell, Fackelmann, Ferrari, Fi...","[Fichte, Fingerhut, Feldsalat]"
g,"[Gera (Deutschland), Gerolstein (Deutschland),...","[Georgien, Ghana, Griechenland, Guinea, Gambia]","[Ganges (Indien), Gera (Deutschland), Green Ri...","[Guido, Georg, Gerald, Gesine, Gerda, Greta]","[GÃ¤rtner, Gleisbauer, Geologe, GerÃ¼stbauer]","[Giraffe, Gnu, Goldfisch, Gazelle, Gepard]","[Gabor, Gardena, Garmin, Garnier, Gazelle, Geo...","[GrÃ¼nkohl, Gerste, Ginster, Gras, Gummi Baum]"
h,"[Hannover (Deutschland), Herne (Deutschland), ...","[Haiti, Honduras]","[Havel (Deutschland), Hunte (Deutschland), Hud...","[Hanna, Hans, Hermine, Henry, Harry, Henrik, H...","[Hausmeister, Historiker, HundezÃ¼chter]","[Hermelin, Hase, Hund, Huhn, Hornisse]","[Haba, Hagen, Haix, Hama, Hecht, Hexal, Hollis...","[Haselnuss, Heide]"
i,"[Ingolstadt (Deutschland), Iserlohn (Deutschla...","[Indien, Indonesien, Irak, Iran, Island, Israel]","[Isar (Deutschland), Inn (Deutschland), Indus ...","[Igor, Ingo, Ida, Ina]","[Ingenieur, Imker, IT-Techniker, Informatiker,...","[Igel, Iltis, Islandponny, Ibericoschwein]","[Icepeak, Ideal, Ikea, Indigo, Intex]","[Iris, Ingwer, Ilex]"
j,"[Jena (Deutschland), JÃ¼lich (Deutschland), Jev...","[Jamaika, Jemen, Japan]","[Jagst (Deutschland), Jade (Deutschland), Jang...","[Jan, Jana, Johan, Johanna, JÃ¶rdis, JÃ¶rk, JÃ¶rn]","[Journalist, Jugenderzieher, Justizwachmeister]","[Jaguar, JunikÃ¤fer]","[Jack Jones, Jack Wolfskin, Jaguar, Jako, Jana...","[Johannes Beere, Jasmin, Johannes Kraut, Josta]"
k,"[KÃ¶ln (Deutschland), Kassel (Deutschland), Kap...","[Kambodscha, Katar (und nicht Qatar im deutsch...","[Kyll (Deutschland), Kinzig (Deutschland), Kon...","[Kerstin, Kai, Karl]","[KÃ¼ster, Kantor, Konditor, Kardiologe, Kanalba...","[Kuh, Katze, Kamel, Kolibir, Kholmeise, Kohlwe...","[K Swiss, Kappa, Kampa, KangaRoos, Karl Lagerf...","[Kirsche, Klee]"
l,"[Ludwigshafen (Deutschland), Ludwigsburg (Deut...","[Lettland, Libanon, Liberia, Libyen, Luxemburg]","[Lech (Deutschland), Lippe (Deutschland), Lahn...","[Lara, Leonie, Lina, Leon, Laureen]","[Landwirt, LogopÃ¤de, Lehrer, Lagerist]","[Leopard, Lama, LippenbÃ¤r, LÃ¶we]","[Louis Vuitton, Lacoste, Lafuma, Lands End, La...","[Litchi, Lavendel, Liane]"
...,...,...,...,...,...,...,...,...
o,"[Oldenburg (Deutschland), Olpe (Deutschland), ...","[Oman, Ã–sterreich]","[Oder (Europa), Oker (Deutschland), Orinoco (S...","[Ole, Olaf, Otto]","[Orthopaedieschuhmacher, Operationstechnischer...","[Orang-Utan, Ochse, Okapi]","[Oneal, Oneill, Oakley, Obi, Odlo, Old Spice, ...","[Osterglocke, Oregano]"
p,"[Potsdam (Deutschland), Paderborn (Deutschland...","[Polen, Portugal, Panama, Pakistan, Peru]","[Pader (Deutschland), Peene (Deutschland), PrÃ¼...","[Phillip, Paul, Peter, Pascal]","[Physiotherapeut, Podologe, Produktionstechnol...","[Pferd, Pinguin, Palmkakadu]","[Parkside, Pelikan, Peter Hahn, Philips, Pikol...","[Petersilie, Pfeffer, Papaya, Paprika]"
q,"[Quickborn (Deutschland), Quedlinburg (Deutsch...",[Es gibt kein Land mit dem Anfangsbuchstaben Q],"[Queich (Deutschland), Queis (Polen), Quâ€™Appel...",[Quinn],[QualitÃ¤tsmanager],"[Qualle, Quastenflosser]","[Q&Q, Qdo, Quadra, Quaker, Qualitex, Quick Sta...",[Quitte]
r,"[Regensburg (Deutschland), Rheine (Deutschland...","[Ruanda, Russland, RumÃ¤nien]","[Rhein (Deutschland), Ruhr (Deutschland), Rur ...","[Rainer, Rene, Rolf, Rudolf]","[Rechtsanwaltsfachangestellter, Restaurantfach...","[Rentier, Rotfuchs, Riesentrappe]","[Rabe, Rainbow, Ralph Lauren, Rauch, Reebok, R...",[Rote Beete]
s,"[Siegen (Deutschland), Siegburg (Deutschland),...","[Spanien, Slowakei, Schweiz, Senegal, Syrien, ...","[Sieg (Deutschland), Spree (Deutschland), Schw...","[Sandra, Siegfried, Sabina, Sabrina, Simone, S...","[Schauspieler, Schornsteinfeger, Sportlehrer, ...","[SchildkrÃ¶te, Schnecke, Seehund, Seepferdchen,...","[S Oliver, Salewa, Salomon, Samsung, Saucony, ...","[Salbei, Seegras, Salat, Sonnenblume]"
t,"[TÃ¼bingen (Deutschland), TÃ¶nning (Deutschland)...","[Thailand, TÃ¼rkei, Turkmenistan, Tunesien, Tai...","[Trave (Deutschland), Tauber (Deutschland), Th...","[Timo, Tammo, Tim, Tom, Torben, Tina, Thomas, ...","[Textillaborant, Textilreiniger, Textil und Mo...","[Tiger, Tintenfisch, Taube, Thunfisch, Tapir]","[Tomaris, Tat Onka, Tchibo, Tefal, Tesa, The N...","[Tomate, Tanne, Tulpe, Tabak, TÃ¼pfelfarn, Thym..."
u,"[Ulm (Deutschland), Uelzen (Deutschland), Unna...","[Uruguay, Ukraine, Ungarn, USA, Uganda]","[Urft (Deutschland), Unstrut (Deutschland), Ur...","[Ursula, Ute, Uwe]","[Uhrmacher, Umweltschutztechnischer Assistent]","[Uhu, Uferschnepfe, Uferschwalbe, Uganda-Giraffe]","[Ufo, Uhu, Umbro, Under Armour, Unicorn, Unime...",[Ulme]
v,"[Viersen (Deutschland), Verl (Deutschland), Ve...","[Vanuta, Venezuela, Vietnam, Vereinigte arabis...","[Vechte (Deutschland), Vils (Deutschland), Vaa...","[Valentia, Valenta, Valene, Valencia, Valantin...","[Veranstaltungskaufmann, Verfahrenstechnologe,...","[VielfraÃŸ, Vierauge, Vipern, Vergoldeter Flohk...","[Volkswagen, Vans, Vaude, Velux, Venice Beach,...",[Veilchen]
w,"[Wuppertal (Deutschland), Werne (Deutschland),...",[WeiÃŸrussland],"[Weser (Deutschland), Werra (Deutschland), Wup...","[Wolf, Willi, Winnie, Werner, Wilhelm, William...","[WÃ¤rme, KÃ¤lte und Schallschutzisolierer, Wasse...","[Wacholderdrossel, WachtelkÃ¶nig, Waldammer, Wa...","[Wagner, Weber, Wehncke, Wella, Wesco, Wmf, Wo...","[Weintraube, Waltmeister]"
x,"[Xanten (Deutschland), Xiamen (China), Xuzhou ...",[Es gibt leider kein Land mit dem Anfangsbuchs...,"[Xiliao He (China), Xar Moron He (China)]","[Xenia, Xandra, Xanthos]","[Xylofonist, Xylofonbauer]","[Xysticus audax, Xenesthis immanis]","[X Cape, X Film, Xavax, Xdrum, Xenox, Xerox, X...",[In Arbeit]
y,[York (England)],[Es gibt leider kein Land mit dem Anfangsbuchs...,"[Yukon (USA), Yalong (China), Yamuna (Inden)]","[Yuna, Yuki, Yuma, Yannick, Yasmin]","[YouTuber, Yachtbauer, Yogalehrer]","[Yak, Yeti-Krabbe, Yellowstone-Elch, Yucatan B...","[Yamaha, Yeti, Ykk, York Fitness]",[Yucca]
z,"[ZweibrÃ¼cken (Deutschland), Zwiesel (Deutschla...","[Zypern, Zentralafrikanische Republik]","[Zschopau (Deutschland), Zusam (Deutschland), ...","[Zoe, Zelda, Zoro, Zoella, Zilla]","[Zahnmedizinischer Fachangestellter, Zahntechn...","[Zander, Zackeneule, ZaunkÃ¶nig, Zebrahai, Zech...","[Zack, Zara, Zeiss, Zero, Zewa, Zwilling]",[Zebragras]

# Guild wars mounts types

In [145]:
r = requests.get("https://api.guildwars2.com/v2/mounts/types?ids=all").json()
data = pd.DataFrame(r)
data

,id,name,default_skin,skins,skills
0,griffon,Griffon,4,"[4, 16, 23, 25, 27, 34, 40, 50, 53, 62, 75, 77...","[{'id': 40576, 'slot': 'Weapon_1'}]"
1,jackal,Jackal,6,"[6, 14, 22, 28, 30, 33, 39, 46, 49, 56, 68, 87...","[{'id': 46089, 'slot': 'Weapon_1'}]"
2,raptor,Raptor,1,"[360, 1, 12, 13, 17, 21, 24, 29, 32, 35, 48, 5...","[{'id': 40409, 'slot': 'Weapon_1'}]"
3,roller_beetle,Roller Beetle,103,"[293, 103, 104, 105, 108, 114, 116, 144, 145, ...","[{'id': 51040, 'slot': 'Weapon_1'}]"
4,skimmer,Skimmer,2,"[2, 19, 26, 36, 37, 44, 45, 47, 52, 57, 70, 83...","[{'id': 41253, 'slot': 'Weapon_1'}]"
5,skyscale,Skyscale,186,"[186, 191, 193, 194, 195, 196, 198, 202, 206, ...","[{'id': 55536, 'slot': 'Weapon_1'}]"
6,springer,Springer,3,"[3, 15, 20, 31, 38, 41, 42, 43, 60, 61, 66, 78...","[{'id': 45994, 'slot': 'Weapon_1'}]"
7,turtle,Turtle,397,[397],"[{'id': 63475, 'slot': 'Weapon_1'}]"
8,warclaw,Warclaw,161,"[161, 162, 163, 164, 165, 166, 204, 207, 236, ...","[{'id': 54912, 'slot': 'Weapon_1'}]"